version: '3'
services:
  api:
    image: "api_template"
    restart: always
    depends_on:
      - "postgres"
    env_file:
      - .variables.env
    ports:
      - "8080:80"
    networks:
      default:

  postgres:
    image: postgres
    restart: always
    env_file:
      - .variables.env
    networks:
      default:
